SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITE
     FROM REST_INFO
     GROUP BY FOOD_TYPE) T
ON R.FOOD_TYPE = T.FOOD_TYPE AND R.FAVORITES = T.MAX_FAVORITE
ORDER BY R.FOOD_TYPE DESC