SELECT YEAR(S.SALES_DATE) AS YEAR, 
    MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT(S.USER_ID)) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT(S.USER_ID)) / T.USER_2021, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE S
JOIN USER_INFO U
    ON U.USER_ID = S.USER_ID
    AND YEAR(U.JOINED) = 2021
CROSS JOIN (
    SELECT COUNT(*) AS USER_2021
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021) T
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
ORDER BY YEAR, MONTH;