SELECT P.PRODUCT_ID, P.PRODUCT_NAME, 
    P.PRICE * O.TOTAL_AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
      FROM FOOD_ORDER
      WHERE PRODUCE_DATE LIKE '2022-05%'
      GROUP BY PRODUCT_ID) O
    ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID