SELECT N.FLAVOR
FROM (SELECT H.FLAVOR, H.TOTAL_ORDER + SUM(J.TOTAL_ORDER) AS TOTAL_ORDER
      FROM JULY J, FIRST_HALF H
      WHERE J.FLAVOR = H.FLAVOR
      GROUP BY J.FLAVOR
      ORDER BY TOTAL_ORDER DESC
        ) N
LIMIT 3