WITH RECURSIVE TEMP AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TEMP
    WHERE HOUR < 23)
SELECT T.HOUR AS HOUR, IFNULL(COUNT(A.ANIMAL_ID), 0) AS COUNT
FROM TEMP T
    LEFT JOIN ANIMAL_OUTS A
    ON HOUR(A.DATETIME) = T.HOUR
GROUP BY T.HOUR
ORDER BY T.HOUR