SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN (SELECT MEMBER_ID, COUNT(REVIEW_TEXT) AS REVIEW_NUM
      FROM REST_REVIEW
      GROUP BY MEMBER_ID
      ORDER BY REVIEW_NUM DESC
      LIMIT 1) T
    ON R.MEMBER_ID = T.MEMBER_ID
JOIN MEMBER_PROFILE M
    ON M.MEMBER_ID = R.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT