SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M
    ON R.MEMBER_ID = M.MEMBER_ID
WHERE M.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(T.REVIEW_NUM)
        FROM (SELECT COUNT(*) AS REVIEW_NUM
             FROM REST_REVIEW
             GROUP BY MEMBER_ID) T
    ))
ORDER BY REVIEW_DATE, REVIEW_TEXT