SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE FISH_TYPE IN (
    SELECT N.FISH_TYPE
    FROM FISH_NAME_INFO N
        JOIN FISH_INFO I
        ON I.FISH_TYPE = N.FISH_TYPE
    WHERE N.FISH_NAME IN ("BASS", "SNAPPER"))
