SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
    GROUP BY CATEGORY) T
    ON T.MAX_PRICE = F.PRICE AND T.CATEGORY = F.CATEGORY
ORDER BY F.PRICE DESC